### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by ReadmeCritic**

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
@Jolg42 fyi this link no longer works

```
 2. [L009] 302 https://partners.adobe.com/public/developer/en/font/5176.CFF.pdf  
 
```

**Comment by ReadmeCritic** [comment]
🎉

**Comment by Jolg42** [comment]
@ReadmeCritic Thank you for the PR 😉

**Comment by ReadmeCritic** [comment]
de rien!

**Pull request merged**
